# Generated by Django 3.2.12 on 2022-03-07 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasstation',
            old_name='price',
            new_name='latest_price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diesel', models.FloatField(blank=True)),
                ('unleaded', models.FloatField(blank=True)),
                ('electric', models.FloatField(blank=True)),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gasstation')),
            ],
        ),
    ]
