# Generated by Django 3.2.12 on 2022-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentPosition',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='unleaded',
            new_name='octane_95',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
