# Generated by Django 3.2.12 on 2022-03-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220322_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='county',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='municipality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
