# Generated by Django 3.2.12 on 2022-03-07 14:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220307_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
