# Generated by Django 3.2.12 on 2022-02-15 12:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220215_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.PositiveIntegerField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0.0 0.0)', srid=4326)),
            ],
        ),
    ]
